### ISSUE TITLE
Add support for apollo-link-batch-http

### ISSUE THREAD

**Issue by ivanvanderbyl** [bgentry/ember-apollo-client#108]
We'd like to use [`apollo-link-batch-http`](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-batch-http) in our app as it seems like it'd work well with Ember Routes and reducing requests as our app loads.

Obviously, this will by default mean it's included in the vendor bundle even if you don't use it, so before we go and add a PR for this, I thought I'd throw out the idea of adding some build time configuration to specify which packages from Apollo are included?

**Comment by bgentry** [comment]
Yes, would absolutely love to see build time config to specify which packages are bundled. My only request is that there is a thoughtful default set to keep the getting started experience simple.

After Apollo Client 2, the core became so much smaller and it became easier to require only the parts you need. But that is not yet the case in this addon.

Excited to see this!

**Comment by zigahertz** [comment]
@bgentry I work with Ivan - just submitted a PR with a basic implementation of this feature. Please let me know what you think!

**Comment by villander** [comment]
This issue can be close now 🎉

**Comment by bgentry** [comment]
Closed by #109!
