### ISSUE TITLE
Resolved data from mutate function doesn't include __typename

### ISSUE THREAD

**Issue by TerminalStar** [bgentry/ember-apollo-client#110]
I came across [this issue](https://github.com/bgentry/ember-apollo-client/issues/34) but it seems like the resolution in https://github.com/bgentry/ember-apollo-client/pull/44 doesn't apply to the data `.mutate` resolves to.

So if you've got something like this (using ember-concurrency, hence the `yield`):
```js
const response = yield this.get('apollo').mutate({
  mutation,
  variables
});
```

`response.__typename` is undefined.

I've come across the problem because I'm trying to ensure consistency with data in ember-data and want to use [`store.push`](https://emberjs.com/api/ember-data/3.0/classes/DS.Store/methods/push?anchor=push) to do so, for which you need to pass the model type.

As suggested in the previous issue, I can use `typename: __typename` in the graphql declaration as a workaround, but was wondering if it's an intentional inconsistency that `mutate` still uses `Ember.copy` rather than `copyWithExtras`?

**Comment by TerminalStar** [comment]
@bgentry Of course! Would you like me to change all instances of `Ember.copy`? It looks like `.query` still uses it too.

**Comment by bgentry** [comment]
Yes please! Thank you!!

**Comment by bgentry** [comment]
@TerminalStar did you get a chance to try making these changes? any issues you ran into?

**Comment by TerminalStar** [comment]
Sorry, I was ill all of last week so didn't get a chance - hoping to get it
done this weekend!

**Comment by bgentry** [comment]
@TerminalStar sorry to hear that! Hope you're feeling better. Was only checking in because I plan to make the `v1.0` release soon and would love to include this fix. But if it doesn't make it that's fine bc it'll work as a bug fix.

**Comment by TerminalStar** [comment]
@bgentry apologies for taking so long! I've a PR up [here](https://github.com/bgentry/ember-apollo-client/pull/116) if you could take a look?

**Comment by bgentry** [comment]
@TerminalStar you rock, thank you for taking care of this!
