### ISSUE TITLE
a change to an array item causes entire list to re-render

### ISSUE THREAD

**Issue by bgentry** [bgentry/ember-apollo-client#135]
I've encountered an issue related to array results. This addon uses an Ember `NativeArray` (via `A()`)  to wrap array results, and then [calls `setObjects`](https://github.com/bgentry/ember-apollo-client/blob/73c259e476542c9c317c3ff64ae1f48fe3a67c1a/addon/services/apollo.js#L49) to update the array in place when Apollo Client notifies us about new/changed data on the array.

Unfortunately, it seems that this (at least sometimes) can cause the entire collection of results to re-render when just a single property on an item in the array changes. The specific scenario I'm encountering involves a modal component that invokes a mutation. The collection is being updated with the modified results before the mutation task has finished. At the moment this mutation is being done within the component itself, so the task gets canceled and the finishing steps (such as showing a flash message) don't complete.

How can I avoid this? Is there some other collection type I should be using in ember-apollo-client? Something that is smart enough to know when only one item in the list has changed and avoid re-rendering the entire thing / tearing down all child components?

**Comment by bgentry** [comment]
The issue here was that I wasn't specifying `key="id"` on my `{{#each}}` invocations, so Ember couldn't tell when the objects in my result array were they same. Docs for that are here: https://emberjs.com/api/ember/3.1/classes/Ember.Templates.helpers/methods/each?anchor=each

This is probably a common mistake when using a non-identity-mapped data service in Ember  (i.e. not ember-data). In Apollo's case, it rebuilds immutable objects each time the results are updated, and for an Array ember-apollo-client fully replaces the underlying array using [`setObjects`](https://emberjs.com/api/ember/3.1/classes/Ember.NativeArray/methods/setObjects?anchor=setObjects).

There's also an RFC from @mmun that would allow specifying a function for the `key=` argument, which would tie in nicely to Apollo's `dataIdFromObject`. Hopefully in the future we can use that to make it easier out-of-the-box since you essentially already need to inform Apollo about how to generate a unique identifier for your objects.

**Comment by viniciussbs** [comment]
Interesting. I'll try that. Since my backend is written using [Absinthe Relay](https://github.com/absinthe-graphql/absinthe_relay), I already have unique global IDs - it's something like `"User:42"` encoded using Base64.
