### ISSUE TITLE
apollo-link-error not exposed

### ISSUE THREAD

**Issue by youroff** [bgentry/ember-apollo-client#137]
Documentation (https://github.com/bgentry/ember-apollo-client#apollo-service-api) mentions use of `onError`, which I believe is exposed by `apollo-link-error`. However it seems not to be imported by `ember-apollo-client`. Should this be fixed, or it's meant this way so I included on my side if I need it?

**Comment by viniciussbs** [comment]
Some one on my team reported something similar to me but I still haven't found to take a look at it to see what's going on. README says that theses dependencies are exposed by this addon:

- apollo-client
- apollo-cache
- apollo-cache-inmemory
- apollo-link
- apollo-link-context
- apollo-link-http
- graphql
- graphql-tag
- graphql-tools

Seams like `apollo-link-error` is not exposed by default. You probably need to follow the [configuration steps](https://github.com/bgentry/ember-apollo-client#configuration) to include optional packages support.

**Comment by youroff** [comment]
Yeah, that's what I did basically. I just included `apollo-link-error`, which was super easy with `ember-auto-import`, and it worked.

**Comment by viniciussbs** [comment]
Should we wait for a decision about auto-import thing (#145) ?

**Comment by bgentry** [comment]
@viniciussbs I haven't had the time to look at #145 and probably won't be able to do so in the near future, though I am always open to others doing so. No need to wait for it, you'd just be adding another package to the list.

**Comment by bgentry** [comment]
Closing this old issue, please reopen if still a problem. Also PRs welcome if so :)
