### ISSUE TITLE
Remove unnecessary zero-dependency computed property

### ISSUE THREAD

**Issue by mike-north** [bgentry/ember-apollo-client#143]
this
https://github.com/bgentry/ember-apollo-client/blob/5296032ff0b10ac3bd9bebf6cca8f56946c90929/addon/mixins/base-query-manager.js#L8-L10

does not need to be a computed property. If you don't care about lazy instantiation, you could just
```js
{
   init() {
       this._super(...arguments);
       // Each instance gets its own query manager
       this.apollo = this.get('apolloService').createQueryManager();
   }
}
```
If you do care about laziness
```js
{
    _apolloQm: null, // Each instance gets its own query manager
   get apollo() {
       if (!this._apolloQm) { // Instantiate (and cache) on first ask
          this._apolloQm = this.get('apolloService').createQueryManager();
      }
      return this._apolloQm;
   }
}
```
In either case, existing consumers will not be affected. `Ember.Object#get` will work with all above approaches

**Comment by bgentry** [comment]
Thanks @mike-north :v:

I don't think the laziness matters here as the empty query manager is _very_ lightweight. Any chance you could PR your `init()` idea?
