### ISSUE TITLE
bug: Engine support

### ISSUE THREAD

**Issue by jasonmit** [bgentry/ember-apollo-client#152]
Engines, and likely nested addon, the following throws since `this.app` is `undefined`: https://github.com/bgentry/ember-apollo-client/blob/master/index.js#L20

What I think should happen is it should walk up the parent hierarchy until it finds a parent that implements the apollo config that it's looking for.  In the case of an engine, it would likely mean the engine's index.js would have the config hanging off it.  Otherwise, it would continue up to the host app which might implement the config.

A quick fix would be to read the config off the host app (which is currently implied by today's implementation by replacing `this.app` with something like `this._findHost()`.  That's currently what I'm doing on my fork: https://github.com/jasonmit/ember-apollo-client/blob/master/index.js#L21-L22

Thoughts?  I can implement either fix but would like to gather consensus first.

**Comment by viniciussbs** [comment]
[`_findHost` is a private function](https://github.com/ember-cli/ember-cli/blob/9398e1936f708f950e7c81aa35f046c104954811/lib/models/addon.js#L676), so we shouldn't rely on it. How other addons handle this issue?

About `ember-auto-import`: related to #145.

**Comment by jasonmit** [comment]
It is.  add-ons, like mirage, do the while loop that you see with _findHost().

**Comment by dfreeman** [comment]
If feasible, I'd lean toward using `ember-auto-import` over adding more logic to the Webpack resolution. Things get hairy when you start to consider what happens when both the host and an engine depend on `ember-apollo-client`, or two engines do — it would be great to lean on the solutions for those scenarios already implemented in auto-import.

**Comment by jasonmit** [comment]
> Things get hairy when you start to consider what happens when both the host and an engine depend on ember-apollo-client, or two engines do — it would be great to lean on the solutions for those scenarios already implemented in auto-import.

Totally agree @dfreeman.  Currently ember-auto-import [doesn't have a solve for this](https://github.com/ef4/ember-auto-import/issues/39).   So that will need to happen before `ember-apollo-client` works properly with engines.

**Comment by bgentry** [comment]
Absolutely on board with switching to `ember-auto-import`, I just haven't had the time to do it myself yet.

**Comment by jasonmit** [comment]
Resolved in 2.0.0-beta.1, thanks!
