### ISSUE TITLE
Problem using async helpers

### ISSUE THREAD

**Issue by raphaelns-developer** [bgentry/ember-apollo-client#153]
After updating my app to Ember version 3.2 the helpers like `click` or `settled` are not waiting the queries to finish.
I did a little example to show the error:  https://ember-twiddle.com/6fea6c57693c2cd14312bdf4293f3778?openFiles=twiddle.json%2Ctemplates.components.my-component.hbs

If you change the Twiddle depencies to Ember 3.1 you will se that the tests pass.

**Comment by bgentry** [comment]
Hmm, I am using this addon in v3.3 and all of my tests have been converted to async. No issues here, so I suspect the problem you're encountering is related to something else.

I don't have the time to dig deeper at the moment though, maybe somebody else can take a look?

**Comment by viniciussbs** [comment]
Hi, @bgentry. @raphaelns-developer works with me. We will update the Twiddle with an example using just `fetch` instead of `Apollo` to get the same JSON to see if it works or not.

**Comment by viniciussbs** [comment]
Looks like its related to https://github.com/emberjs/ember-test-helpers/issues/339.

**Comment by viniciussbs** [comment]
@bgentry he updated the Twiddle to use only `ember-fetch` to exposed the bug and posted on `ember-test-helper`. You may close this issue.

**Comment by viniciussbs** [comment]
@bgentry I guess we should reopen this issue.

## When we face this issue:

There are some scenarios when `settled` does not wait for some async calls:

- when there is a watched query and we refetch the query;
- when there is a watched query and we fetch more data;
- when we send a mutation with the option `refetchQueries`;

We just increment the ongoing counter for the first fetch. When we call `refetch`, `fetchMore` or set `refetchQueries` when sending a mutation, we do not register those ongoing requests.

## How we solved this issue

### Query Manager

```js
import QueryManager from 'ember-apollo-client/apollo/query-manager';

export default QueryManager.extend({
  refetch(opts, observable) {
    return this.apollo.refetch(opts, observable);
  },

  fetchMore(opts, observable) {
    return this.apollo.fetchMore(opts, observable);
  }
});
```

### Service

```js
import ApolloService from 'ember-apollo-client/services/apollo';
import QueryManager from 'my-app/apollo/query-manager';

export default ApolloService.extend({
  createQueryManager() {
    return QueryManager.create({ apollo: this });
  },

  refetch(opts, observable) {
    return this._waitFor(observable.refetch(opts));
  },

  fetchMore(opts, observable) {
    return this._waitFor(observable.fetchMore(opts));
  },

  mutate(opts, resultKey) {
    if (Ember.testing) {
      opts.awaitRefetchQueries = true;
    }

    return this._super(opts, resultKey);
  }
});
```

## Examples of how we use those functions:

- `fetchMore` for pagination
- `refetch` for searches
- mutation with `refetchQueries` for deletes

## Disclaimer

We are not mocking our API. Our API has a sandbox server for tests. Maybe mocks are obfuscating this issue.
