### ISSUE TITLE
shorter mixin imports?

### ISSUE THREAD

**Issue by bgentry** [bgentry/ember-apollo-client#156]
What do folks think of changing the imports from this:

```js
import ComponentQueryManager from "ember-apollo-client/mixins/component-query-manager";
```

to this:

```js
import { ComponentQueryManager } from "ember-apollo-client/mixins";
```

or even this:

```js
import { ComponentQueryManager } from "ember-apollo-client";
```

IMO that's a big improvement. Any objections?

**Comment by viniciussbs** [comment]
The last one, for me. But it would come in a major version, right?

**Comment by viniciussbs** [comment]
Or have both and deprecate the old one.

**Comment by bgentry** [comment]
Yes, #145 will probably be a breaking change anyway. Although it would be good to introduce the new import paths in a 1.x release and also deprecate the old ones to allow for a cleaner migration.

If anybody wants to take a stab at this before I get to it, please do! :pray:

**Comment by bgentry** [comment]
I took care of adding the new imports, but I would also like to deprecate the old ones (prior to any 2.x betas that include ember-auto-import). Could use help with that part.
