### ISSUE TITLE
Assertion Failed: Expected hash or Mixin instance, got [object Undefined]

### ISSUE THREAD

**Issue by jfrux** [bgentry/ember-apollo-client#161]
Everytime I do this:
```javascript
import Route from "@ember/routing/route";
import { RouteQueryManager } from "ember-apollo-client";



export default Route.extend(RouteQueryManager, {
  //...
});
```

I get this:
`Assertion Failed: Expected hash or Mixin instance, got [object Undefined]`

**Comment by josemarluedke** [comment]
I'm afraid that this new way of importing is not yet released on NPM. It was recently added here in this PR: #160. I hove this can help you out.

**Comment by bgentry** [comment]
Oops, I’ll get a release out later today. In the mean time you can pull from GitHub or use the old import paths.

**Comment by jfrux** [comment]
You guys are like... pure <3 bruh'z.
I'm sorry for the ignorance!  I hate being "that guy".  Keep being you and doing all you do.

Will try this!

**Comment by viniciussbs** [comment]
@jfrux You are that guy who reminded us about the release! Thanks for that. ;)

**Comment by bgentry** [comment]
New version v1.0.4 published on npm, cheers :v:
