### ISSUE TITLE
working with ember-data

### ISSUE THREAD

**Issue by marsh73** [bgentry/ember-apollo-client#275]
I'm trying to find some good examples of using ember-apollo-client queries to hydrate ember data store. I realize that apollo has it's own caching which handles state management. I'm not sure if this has to be one or the other or if there is a clean migration path as i build out my graphql proxy to switch from REST

**Comment by bgentry** [comment]
ember-apollo-client does not integrate with ember-data in any way and isn't intended to, sorry!
