### ISSUE TITLE
Design Pattern / Component Question

### ISSUE THREAD

**Issue by dephora** [bgentry/ember-apollo-client#28]
Scenario: A few routes in my app will contain recent activity / notifications components. Additionally, these can be displayed in a popover list from a toolbar on any route. For example, on the main dashboard, I will have an activity feed summary which shares state with the toolbar popout, but likely not the same component as the toolbar version might have limited features.

The conflicting opinions on Ember Data deal with when it's appropriate to inject the store into a component.

I'm currently passing the data retrieved from my graphql query in the route to both components. I'm not a fan of this method due to one of the components being deeply nested. I would rather just do a query / mutation from the component itself. Is this a bad idea / design pattern under certain circumstances (referring to the arguments about doing this with Ember Data). ie, will this cause data sync issues or anything similar?  

Judging by "In a component, this cleanup is typically done with a willDestroyElement hook." from the docs, I assume this isn't an issue. 

Thanks in advance.

**Comment by n1ru4l** [comment]
Since all queries subscribe to a single apollo store which  there shouldn't be any problems with syncing.
I am really looking forward to use this package soon! Here I created a fiddle on how I would design my query components: https://ember-twiddle.com/738df6224819f0ab4209e6748c96766e?openFiles=components.query-wrapper.js%2Ctemplates.components.query-wrapper.hbs

**Comment by dephora** [comment]
Great, appreciate the info @n1ru4l. I personally haven't had issues with the Ember Data store having issues when breaking out of 'Data Down' with injecting as a service but I guess there are cases out there as it's brought up often.

**Comment by n1ru4l** [comment]
We also injected the store service in one of our projects and we also did not experience any issues with that.
