### ISSUE TITLE
Why is the default dataIdFromObject implementation overridden?

### ISSUE THREAD

**Issue by n1ru4l** [bgentry/ember-apollo-client#29]
Apollo-client already ships with a [`dataIdFromObject` implementation](http://dev.apollodata.com/react/cache-updates.html#normalization). I do net see the point in overwriting the default implementation (which is much more flexible) with one that only fits users that use totally unique ids.

If there is not any specific reason for this, I could do a pull request.

**Comment by bgentry** [comment]
@n1ru4l it may be a relic from this addon being extracted from my app. As you say, there is a default implementation ([here, actually](https://github.com/apollographql/apollo-client/blob/dbbd4dd9983f878e114378a9997e70df0f565b7b/src/ApolloClient.ts#L102-L112)). It's also possible that default implementation wasn't there or worked differently at the time this addon was originally cooked up.

Can you send a PR? If so, please also change the readme to add yourself to the contributors list :v:

**Comment by n1ru4l** [comment]
Done 👍
