### ISSUE TITLE
Should there be an integration for generating persisted queries?

### ISSUE THREAD

**Issue by n1ru4l** [bgentry/ember-apollo-client#31]
I was wondering if it would make sense to somehow integrate https://github.com/apollographql/persistgraphql into this addon?

E.g. by adding a config option to generate persisted queries during the production build step.

What is your opinion on this @bgentry?

**Comment by bgentry** [comment]
I don't personally have a need for this but I'd be happy to include this functionality in the addon.

**Comment by bgentry** [comment]
Closing this as inactive for now, feel free to reopen if it's something you still need / if you have ideas on it :)
