### ISSUE TITLE
Network error: Cannot add/remove sealed array elements after update Chrome to version 60

### ISSUE THREAD

**Issue by viniciussbs** [bgentry/ember-apollo-client#37]
I've updated Chrome to version 60 (stable version released yesterday) and now, when I fetch the very first query on my app, I face this error: `Network error: Cannot add/remove sealed array elements`.

![image](https://user-images.githubusercontent.com/245791/28633249-85768272-7209-11e7-8d01-629f476d9ebf.png)

It's seems like it's a problem with `apollo-client`, but we are using a very outdated version of it.

@bgentry @dfreeman @n1ru4l Sorry to bother you, but are you facing this problem too?

**Comment by bgentry** [comment]
@viniciussbs haven't restarted Chrome yet to find out but that sounds like a big issue. Going to check it out as soon as I can. In the mean time, I'm available for at least the next several hours to help w/ any PRs that address this (perhaps by upgrading the apollo-client dependency?)

**Comment by bgentry** [comment]
@viniciussbs I'm not seeing this on my app after updating Chrome, either in dev or prod. I'm currently on:

```
> __APOLLO_CLIENT__.version
"1.2.2"
```

**Comment by viniciussbs** [comment]
@bgentry, I've found the problem. My Apollo client has an middleware that was doing:

```javascript
window.navigator.languages.unshift(language);
```

The array returned by window.navigator.languages is sealed now on Chrome 60.

**Comment by viniciussbs** [comment]
But I still think it's a good idea to update apollo-client version. Maybe it has a better error reporting.
