### ISSUE TITLE
Apollo Imperative Store Usable

### ISSUE THREAD

**Issue by DevanB** [bgentry/ember-apollo-client#38]
I'm going to assume the answer is no, but has the [imperative store](https://dev-blog.apollodata.com/apollo-clients-new-imperative-store-api-6cb69318a1e3) API been setup in this client?

This makes it so you can update the local Apollo store after mutations. This would work perfectly hand-in-hand since `watchQuery` is being used by default by this Apollo client implementation.

**Comment by bgentry** [comment]
Nope. Would love to see that. Unsure if it's orthogonal to #20 or if it should be tackled at the same time. Do you have an idea of what changes would need to be made to support this?

**Comment by DevanB** [comment]
I'll read through #20 closer tomorrow, but a quick skim tells me yes and no. Yes, it's helpful, because those updates would automatically be shown, but no, because there is a separate API for writing directly to the local store. The only approach I know of this so far is how `react-apollos` handles it. I'll dig into that implementation and see what I can reason about.

Thanks for the quick response! I'm excited to see people actively finding this library and inquiring about it. Makes it a stronger library in the end!

**Comment by DevanB** [comment]
Okay, I did some more research on this.

Apollo's `mutate` can take an optional [`update` function](http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.mutate) which is called after the server responds. Here is a simple example that adds a new link that was just mutated (`createLink`) into the store cache:

```
update: (store, { data: { createLink } }) => {
  const data = store.readQuery({ query: ALL_LINKS_QUERY })
  store.writeQuery({ query: ALL_LINKS_QUERY, data })
}
```

The best I can tell, I would propose that this function happen within [`mutate`'s `then` block](https://github.com/bgentry/ember-apollo-client/blob/master/addon/services/apollo.js#L84). Looks like you should take the current `store`, the result of the mutation and pass them into the `update` function. The user then uses the Apollo API to manipulate the store.

Does this make sense?

**Comment by n1ru4l** [comment]
I'm heavily using the imperative store api for optimistic ui updates. This is a apollo-client feature not an react-apollo feature. You can just pass an update function to the apollo services mutate function.

Here some example:

```javascript
apollo.mutate({
    mutation: DeleteWrapperMutation,
    variables: {wrapperId},
    optimisticResponse: {
        __typename: `Mutation`,
        deleteWrapper: true,
    },
    update(proxy, {data: {deleteWrapper: success}}) {
        if (!success) {
            return
        }
        const questionnaireFragment = proxy.readFragment({
            fragment: BlockMutateWrappersFragment,
            fragmentName: `BlockMutateWrappersFragment`,
            id: blockFragmentId,
        })
        questionnaireFragment.wrappers = questionnaireFragment.wrappers
            .filter(wrapper => wrapper.id !== wrapperId)
            .sort((w1, w2) => w1.sort - w2.sort)
        questionnaireFragment.wrappers.forEach((wrapper, i) => wrapper.sort = i + 1)

        proxy.writeFragment({
            fragment: BlockMutateWrappersFragment,
            fragmentName: `BlockMutateWrappersFragment`,
            id: blockFragmentId,
            data: questionnaireFragment,
        })
    },
})
```

**Comment by DevanB** [comment]
@n1ru4l This is great news! I *literally* just got it working, however I'm seeing odd warnings in my console about `__typename` missing and what could be warnings caused by other documents in my store that don't meet the schema I built.

@bgentry I'd love to help you and others that use this library by writing some documentation on the README on the `update` options usages; if this is something you would be prepared to merge in.

Additionally, you will probably see an influx of traffic to this add-on in the next 2-3 weeks as I wrap up the screencast and tutorial writing and it is published on [How To GraphQL](http://howtographql.com). I'd love to dedicate more time to helping maintain this library if you are looking for others to help you.

Thanks again!

**Comment by n1ru4l** [comment]
@DevanB I think it would be enough to add a link to http://dev.apollodata.com/core/apollo-client-api.html#ApolloClient.mutate would be enough for the moment.
However having docs like the react-apollo docs would definitely encourage more users to use emebr-apollo-client 🤔
