### ISSUE TITLE
_apolloUnsubscribe issue

### ISSUE THREAD

**Issue by xrexonx** [bgentry/ember-apollo-client#39]
Hi. 
I'm new to this `ember-apollo-client` addon. I'm following the Usage instructions. Already imported the UnsubscribeRoute on route file but still getting this error `Uncaught TypeError: Cannot set property '_apolloUnsubscribe' of undefined`

What did I missed on this and how to fix?

And also for this example:
```js
query human($id: String!) {
  human(id: $id) {
    name
  }
}
```
Does it also requires a `app/models/human.js` for this?

Thanks,
Rexon

**Comment by DevanB** [comment]
Hey @xrexonx!

Can you share your route file here?

**Comment by xrexonx** [comment]
Hi @DevanB 
Thanks for the reply.
Here's the route file

```js
// app/dashboard/route.js
import Ember from 'ember'
import UnsubscribeRoute from 'ember-apollo-client/mixins/unsubscribe-route'
import query from '../gql/queries/book'

const { Route, inject: { service } } = Ember

export default Route.extend(UnsubscribeRoute, {
  apollo: service(),
  book: service(),
  bookDetailService: service('book-details'),

  model() {
    // this query response data already in GraphQL network chrome devtools
    return this.get('apollo').query({ query, variables: { isbn13: '9780078028991'}  }, 'book')
  }

  resetController(controller, isExiting, transition) {
    if (isExiting) this.get('bookDetailService').reset();
  },

  actions: {
    didTransition() {
      this.get('bookService').checkSessionedBooks();
    }
  }
  
})

```
Why does it respond a `Uncaught TypeError: Cannot set property '_apolloUnsubscribe' of undefined` on browser console?.

And also, Is it possible to have a query in controller or components file like this?
```js
// some controller or components file in init functions
this.set('data', this.get('apollo').query({ query, variables: { isbn13: '9780078028991'}  }, 'book'))
```
Thanks a lot and have a nice weekends.
~ Rexon

**Comment by DevanB** [comment]
@xrexonx 

Your route file looks correct to me. Are you using the `UnsubscribeRoute` mixin anywhere else?

Yep! You can have a query/mutation anywhere you can inject the `apollo` service and call the `query`, `queryOnce`, or `mutate` methods.

**Comment by ivanvanderbyl** [comment]
What was the fix for this issue? I'm seeing the exact same issue when using watchQuery within a component.

**Comment by bgentry** [comment]
@ivanvanderbyl are you getting an `undefined` result back from your `warchQuery` call (perhaps bc you’re calling a key that doesn’t exist in the response)?

I think there’s a bug related to that scenario but not sure of a good fix for it.
