### ISSUE TITLE
Mocking responses for development

### ISSUE THREAD

**Issue by dhdemerson** [bgentry/ember-apollo-client#40]
Is there an established or recommended way to mock data and GraphQL responses for development purposes?

**Comment by bgentry** [comment]
The project's tests contain some examples of using Pretender to do this. Check out [how that's set up](https://github.com/bgentry/ember-apollo-client/blob/master/tests/helpers/start-pretender.js) to enable auto-mocking by Apollo Client, and the tests that utilize it (with expectations or customized responses): https://github.com/bgentry/ember-apollo-client#testing

**Comment by dhdemerson** [comment]
Hey, thanks for the quick reply. I saw that bit in the documentation but I thought it was specific to testing, can that approach also be used for mocking responses for applications running in development (similar to Mirage)?

**Comment by n1ru4l** [comment]
You could implement a mock networkInterface, like here:
https://github.com/apollographql/react-apollo-error-template/blob/master/src/graphql/networkInterface.js

**Comment by bgentry** [comment]
Yes, I believe the solution to this is to build a custom `networkInterface` and provide it in the config for the Apollo service. I'm going to close this as I don't believe there's anything to do implementation-wise, but please reopen if you think that's incorrect.
