### ISSUE TITLE
Apollo Client 2.0

### ISSUE THREAD

**Issue by bgentry** [bgentry/ember-apollo-client#54]
Apollo Client 2.0 is just around the corner. Here's a general summary of how to migrate: https://github.com/apollographql/apollo-client/blob/master/Upgrade.md

I haven't yet studied it in detail, but there is likely a bit of work to do to keep ember-apollo-client up-to-date with it.

**Comment by viniciussbs** [comment]
Yes, I was thing about it. The middleware thing we have you go away. I'll have to think about how to plug links easily etc.

**Comment by bgentry** [comment]
Apollo Client 2.0 was officially released today: https://dev-blog.apollodata.com/apollo-client-2-0-5c8d0affcec7

I still haven't had the time to look at what's involved in supporting it here. If anybody else wants to take a crack at it, feel free!

**Comment by viniciussbs** [comment]
Relevant links:

- https://www.apollographql.com/docs/
- http://apollo-link-docs.netlify.com/docs/link/

I haven't found the updated documentation of the vanilla client.

**Comment by DevanB** [comment]
All documentation has been moved to apollographql.com. Ignore any site that has netlify in it (those are old and not up-to-date.

**Comment by viniciussbs** [comment]
@DevanB Could you post the relevant links here, please?

**Comment by viniciussbs** [comment]
Here are the docs:

- https://www.apollographql.com/docs/
- https://www.apollographql.com/docs/link/

**Comment by viniciussbs** [comment]
Links will replace middlewares, so we should let users create their own links easily. They will need [links for authentication, error tracking etc](https://www.apollographql.com/docs/link/stateless.html), but links can also be used for [batching requests](https://www.apollographql.com/docs/link/stateful.html).

**Comment by xtagon** [comment]
Are there plans to support this? Is help needed?

My goal is to find a good way to use the Absinthe GraphQL Subscriptions with Ember, and it uses the new Apollo Link feature: https://github.com/absinthe-graphql/absinthe-socket/tree/master/packages/socket-apollo-link

**Comment by bgentry** [comment]
Definitely something I want to support soon. In fact @villander started working on it this week but ran into some Webpack issues.

**Comment by xtagon** [comment]
Awesome! Feel free to reach out if you need help testing or anything like that. I'd be happy to contribute.

**Comment by bgentry** [comment]
I've started on this in #79. I have it working in my own app, but haven't yet documented the changes. There are also some config API issues that will need sorting out.

In either case, I'd appreciate some help testing it with other apps. The upgrade was pretty straightforward in my own app. Please post in that PR if you encounter any issues!
