### ISSUE TITLE
Issue (not updating while adding a new record)

### ISSUE THREAD

**Issue by ivanhueso** [bgentry/ember-apollo-client#70]
Hi,
Lets have this scenario where:
1. I loop and display throw a list of users from returned model using watchQuery.
2. I update one existing users from the list via a mutation successfully, and all changes reflects on the already displayed list without any issues.
3. I do the same by instead this time I add a new user successfully through a mutation but then on the list it doesn't show the new record I've added. Even if I get out of the route and came back.

Why is this happening, is there a solution?
Best,
Ivan

**Comment by bgentry** [comment]
Hi @ivanhueso,

These are some fundamental concepts for how Apollo Client works. For a given query (say a list of users), its result is kept in Apollo Client's cache. That result is not re-fetched from the server unless you provide a different `fetchPolicy` in your query options, such as `cache-and-network`.

What you could also do is [manually update the cache after a mutation](https://www.apollographql.com/docs/react/basics/mutations.html#store-updates) or use [the `refetchQueries` option on `mutate`](https://www.apollographql.com/docs/react/reference/index.html#ApolloClient\.mutate).

I suggest reading more of the Apollo Client docs, specifically the React docs as those are the strongest: https://www.apollographql.com/docs/react/

**Comment by ivanhueso** [comment]
Using `refetchQueries` works. Thank you @bgentry
