### ISSUE TITLE
Upgrade to Ember v3.0

### ISSUE THREAD

**Issue by bgentry** [bgentry/ember-apollo-client#93]
This addon could use an upgrade to the latest Ember version. That would ideally include a conversion of its tests to the new async style.

**Comment by villander** [comment]
I think we can wait for 3.1 because then we will not be forced to write `this.get` and we will leave the addon more at will.

**Comment by josemarluedke** [comment]
Waiting for 3.1 to get away of `this.get` doesn't seem to be a strong case. The addon should still use `this.get` to be able to maintain compatibility for older versions of Ember. The only places that should not rely on `this.get` are tests and the dummy app.

**Comment by villander** [comment]
True @josemarluedke, I was thinking too loud. I think we can go to 3.0 as soon then =D

**Comment by bgentry** [comment]
Yep, the addon itself needs to stick with `this.get` for a long time to come. But we can upgrade our dependencies and our test files to the new async style, which would be nice.
